version: "3"
services:
  web:
    # replace username/repo:tag with your name and image details
    image: jenkinsci/blueocean 
    user: root
    deploy:
      replicas: 1 
      resources:
        limits:
          cpus: "0.3"
#          memory: 50M
      restart_policy:
        condition: on-failure
    volumes:
#      - "/home/ronald:/home"
      - "jenkins-data:/var/jenkins_home"
      - "/var/run/docker.sock:/var/run/docker.sock"
    ports:
      - "8000:8000"
    networks:
      - webnet
volumes:
    jenkins-data:
networks:
  webnet:
